### ISSUE TITLE
Vue file support with recent 'Vue - Official' extension updates

### ISSUE THREAD

**Issue by JayPuff** [yoavbls/pretty-ts-errors#101]
I only installed this awesome extension recently, but with recent changes to the vscode vue language tool extension, it seems that this extension is not formatting the error messages within `.vue` files (It works fine on `.ts` files)

Is anyone else running into this problem, or is this a setup problem on my end for some reason? (Or perhaps an issue with the Vue language tools since there's many issues open currently)

Working just fine on `.ts` files.
![image](https://github.com/yoavbls/pretty-ts-errors/assets/32312545/70254a56-5db3-4b03-bade-b986b63e4239)

On a `.vue` file
![image](https://github.com/yoavbls/pretty-ts-errors/assets/32312545/09df3481-65ee-42c6-806f-c9d8bcb5acef)

Vue Language Tool / Vue - Official extension version: v2.0.10
Vscode version: 1.88.0
Running @builtin js and ts language features *No takeover mode)

**Comment by bordermedia** [comment]
Yep exactly same issue for me.

**Comment by yoavbls** [comment]
Thank you for opening this issue.
Fixed it in #103, published in v0.5.4
