### ISSUE TITLE
TS2322 not rendered correctly

### ISSUE THREAD

**Issue by moritz-t-w** [yoavbls/pretty-ts-errors#105]
**Describe the bug**
ts(2322) is rendererd partly wrong at the end.
These are the relevant properties
```ts
#overlaps!: OverlapConfigurationParameters[];
private async download(file: File<string | MpcdiZip>): Promise<void>
```
**Expected behavior**
each property listed gets its own bullet point

**Original error**
```ts
Type 'Ref<{ name: string; readonly type: "json"; mm: <T extends Convertible = Convertible>(px: T) => T; px: <T extends Convertible = Convertible>(mm: T) => T; ... 18 more ...; toJson: () => string; }>' is not assignable to type 'Ref<MpcdiConfiguration>'.
  Type '{ name: string; readonly type: "json"; mm: <T extends Convertible = Convertible>(px: T) => T; px: <T extends Convertible = Convertible>(mm: T) => T; ... 18 more ...; toJson: () => string; }' is missing the following properties from type 'MpcdiConfiguration': ratio, #overlaps, download
```

**Screenshots**
![Screenshot from 2024-04-30 08-16-06](https://github.com/yoavbls/pretty-ts-errors/assets/90388353/bdadc918-707d-4c95-9050-d6f6b3763901)

> is missing the following properties from type `MpcdiConfiguration`:
> - ratio,
> #overlaps, download

**Comment by kevinramharak** [comment]
Issue is the private property prefix character `#`, I submitted a PR #106

**Comment by yoavbls** [comment]
Thank you, the fix will be there in the next version
