### ISSUE TITLE
In Vue and TS file, error no format， after i installed plugin

### ISSUE THREAD

**Issue by shaobeichen** [yoavbls/pretty-ts-errors#108]
**Describe the bug**
In Vue and TS file, error no format， after i installed plugin

**Expected behavior**
In Vue and TS file, error is formated， after i installed plugin

**Original error**
```ts
interface A {
  a?: string
  b?: number
  c?: {
    d?: string
    e?: number
  }
}

type C = A['c']

const c: C = {
  ddd: 1,
}
```
<code>
Object literals can only specify known properties, and 'ddd' is not in type '{d?: string | undefined; e?: number | undefined;}'. TS2353
</code>

**Screenshots**
![image](https://github.com/yoavbls/pretty-ts-errors/assets/18715564/b1cb8e1b-8086-45eb-b7db-dc76d7e91914)

This is a easy example, error no format, and i found all Vue ts file error is no format, 
i installed plugin, i don't know if it was my use mistake.

**Comment by kevinramharak** [comment]
I think other locales than english are not supported yet, see #27.

**Comment by yoavbls** [comment]
Thank you @kevinramharak

**Comment by kevinramharak** [comment]
I have opened a discussion at #146, any input is welcome!
