### ISSUE TITLE
Support for WebStorm?

### ISSUE THREAD

**Issue by DoooReyn** [yoavbls/pretty-ts-errors#11]
Hi, This plugin is awesome and helpful.
And I am wondering if you have plans to support JetBrains WebStorm.

Best regards.

**Comment by juicyjusung** [comment]
LGTM!

**Comment by Sufiane** [comment]
that would be awesome !

**Comment by avshyz-gs** [comment]
A million times yes

**Comment by GCJ2** [comment]
Would love this as well.

**Comment by hadnet** [comment]
Would love support for VIM users as well!

**Comment by yoavbls** [comment]
It'll be challenging since I don't know Kotlin or how JetBrains extensions work,
But I'll find time to try.
If someone here did write a JetBrains extension, feel free to reach out 🙏🏼

**Comment by yoavbls** [comment]
@hadnet I don't even know how to use Vim (I know only to exit 😅) 
Are Vim plugins can be written in TypeScript?

**Comment by cjsewell** [comment]
Added a request on youtrack, to see if we can get Jetbrains to help support it. Go up vote it!
https://youtrack.jetbrains.com/issue/WEB-60634/Add-support-pretty-ts-errors

**Comment by hronro** [comment]
@yoavbls 

> Are Vim plugins can be written in TypeScript?

Yes, they can!

One of the most LSP implementations for VIM is [coc.nvim](https://github.com/neoclide/coc.nvim), which is written in TypeScript and shares a lot of code from VSCode.

**Comment by Karamuto** [comment]
Would be surely awesome to have Webstorm support!

**Comment by lukasborawski** [comment]
Please! 🙏🏻

**Comment by Buslowicz** [comment]
I am also for it, am using WebStorm for around 9-10 years now, this would be a perfect addition to it!

**Comment by RafalSzczuka** [comment]
That would be lovely!

**Comment by golubeva1ex** [comment]
would be really great +1🫠

**Comment by izakfilmalter** [comment]
Would love this.

**Comment by vasilistotskas** [comment]
would be really helpful 🔥

**Comment by iSplasher** [comment]
I think it might be better to separate the parsing and formatting logic into a different package `pretty-ts-errors-formatter` and then let the community build plugins on top of it.
Could even make it a more generic `error-formatter` with a standardized api to support all kinds of languages.

**Comment by johnsoncodehk** [comment]
See https://github.com/yoavbls/pretty-ts-errors/issues/21#issuecomment-1512932535

**Comment by el-veee** [comment]
Just want to shout out that Webstorm 2023.2 just released and includes improved error formatting out of the box, similar to this extension.

https://www.jetbrains.com/webstorm/whatsnew/

**Comment by IGassmann** [comment]
> Just want to shout out that Webstorm 2023.2 just released and includes improved error formatting out of the box, similar to this extension.
> 
> [jetbrains.com/webstorm/whatsnew](https://www.jetbrains.com/webstorm/whatsnew/)

So happy about this. I wonder though how it compares to this extension.

**Comment by yoavbls** [comment]
I tried it in a few cases and it's really nice!

<img width="705" alt="image" src="https://github.com/yoavbls/pretty-ts-errors/assets/5693018/af0b7be5-30f3-4a8a-8a5a-5258f32ad429">


I didn't spot differences except for the links to typescript.tv and the error literal explanation but I'm waiting for heavy WebStorm users to try and write their impressions 🙂

**Comment by yoavbls** [comment]
So I guess it's considered Done
