### ISSUE TITLE
Not seeing any formatted errors

### ISSUE THREAD

**Issue by jschuur** [yoavbls/pretty-ts-errors#12]
I don't see any new formatting after I enabled (and restarted VS Code, just to be safe) extention:

<img width="1131" alt="CleanShot 2023-04-17 at 07 13 04@2x" src="https://user-images.githubusercontent.com/92457/232398909-d18403b2-83f7-4ae4-9184-0aafcf1f9e94.png">

Could there be some kind of conflict with other extensions?

**Comment by djmisterjon** [comment]
not all case seem covered yet

**Comment by yoavbls** [comment]
I didn't succeed in reproducing it, even with the error lens enabled, did you try to make the error change after you enabled the extension?
Can you provide more information about your VSCode and extension version?

**Comment by yoavbls** [comment]
@johnsoncodehk saw that your screenshot is from an untitled document and is currently not supported. I will add support very soon 🙏🏼
@jschuur

**Comment by yoavbls** [comment]
`v0.3.0` with the fix is out!
You can update now 🙂
