### ISSUE TITLE
[Question, not issue report] Is any possiable to make the pretty errors in the fixed top?

### ISSUE THREAD

**Issue by ChangeHow** [yoavbls/pretty-ts-errors#124]
It's  a great extension, but there's one question confuses me in a long time:

**Can we put the pretty error in the very to  p of popover, or alternatively, hide the original error?**

I think it would a great improvement for user experience but I can't find any solution in the wide internet.

**Comment by yoavbls** [comment]
Hey, unfortunately, it is a known limitation: https://github.com/yoavbls/pretty-ts-errors/issues/3
But there is a CSS hack that allows you to hide the original error in the last comment in the issue
