### ISSUE TITLE
Code blocks containing 'xxx' are not displayed correctly.

### ISSUE THREAD

**Issue by randomVariable2000** [yoavbls/pretty-ts-errors#13]
## ScreenShot
![image](https://user-images.githubusercontent.com/37059674/232401840-ea4b9c9b-a216-49a0-bb45-42b30f01deed.png)

## Case
```typescript
const a = { 'a-a': '11' }

const b:a = '11'
```

**Comment by yoavbls** [comment]
`v0.3.0` with the fix is out 🙂
You can update now
