### ISSUE TITLE
It does not work as expected

### ISSUE THREAD

**Issue by jalalbmnf** [yoavbls/pretty-ts-errors#14]
Hi, thank you for the great extension. I installed this extension and but for some reason, I still get the same ts error style

<img width="922" alt="Screenshot 2023-04-17 104359" src="https://user-images.githubusercontent.com/53921355/232405496-07b122a0-f135-4ce5-8b5e-7fe2265f3427.png">

**Comment by vikvikvr** [comment]
Hi @jalalbmnf , this extension only enhances the style of tooltips (ie. when you hover on red squiggly lines). 

The problems reporter is text based, that's why it stays the same.

**Comment by jalalbmnf** [comment]
Thank you for quick response @vikvikvr
