### ISSUE TITLE
Cannot distinguish the difference between multiple uses of a single quote.

### ISSUE THREAD

**Issue by martmalo** [yoavbls/pretty-ts-errors#20]
`Method's 'this'` got read incorrectly. Probably, incorrect use of `'` or `"`.

<img width="806" alt="image" src="https://user-images.githubusercontent.com/77250222/232703847-6a736cb8-ab6e-44f2-88ab-a5846a4e7fd5.png">

**Comment by yoavbls** [comment]
I think that this regex (in the picture) is causing it,
I'll check if it is resolved when we'll merge a fix.
Until then, can you put here the plain error so I can test it?

**Comment by yoavbls** [comment]
`v0.3.0` with the fix is out!
You can update now 🙂
