### ISSUE TITLE
I see both raw error AND beautify error ( I should see only beautify)

### ISSUE THREAD

**Issue by RoyiNamir** [yoavbls/pretty-ts-errors#31]
Saying I have this error : 
![image](https://user-images.githubusercontent.com/2842123/233269166-4f0fe9dd-317e-4713-b0ab-4f1e22a1beec.png)

When I hover over the error I see this : 

it showes errors in two formats: raw& beautify

![image](https://user-images.githubusercontent.com/2842123/233269276-080aab15-c4ad-4eb1-9aea-de5c0f21f71d.png)

Expected : to see only the beautified error

**Comment by JUSTIVE** [comment]
duplicated with #3

**Comment by yoavbls** [comment]
@RoyiNamir Thank you for opening this issue!
As @JUSTIVE said it's duplicate so lets continue the discussion [here](https://github.com/yoavbls/pretty-ts-errors/issues/3) 🙂
