### ISSUE TITLE
Typing gets laggy (UI hangs for split seconds) when using this extension

### ISSUE THREAD

**Issue by felixfbecker** [yoavbls/pretty-ts-errors#36]
Type: <b>Bug</b>

I absolutely love this extension and can't live without it.
But I noticed that I very consistently have lags in typing when using it (the UI will freeze for split seconds while typing). I don't know what the reproduction steps are, but I used the Extension Bisect tool to identify that this *only* happens when the extension is active (and very consistently) and never when the extension is deactivated.

Extension version: 0.2.8
VS Code version: Code 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:41:48.638Z)
OS version: Darwin arm64 22.3.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|7, 7, 7|
|Memory (System)|32.00GB (0.09GB free)|
|Process Argv|--crash-reporter-id 9d8b3555-0016-4d38-9abf-4a1f6545cfc7|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
nodejswelcome1:30587005
3biah626:30602489
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
a9j8j154:30646983
vsctsb:30705553
functionswalk:30687959
pythonms35:30701012
pythonfmttextcf:30716743

```

</details>

**Comment by rdsedmundo** [comment]
I'm also facing this. I suspected it had to do with this extension since it was the only recent I had added. I see the slowness the most when VSCode runs Prettier upon me saving the file.

**Comment by yoavbls** [comment]
@felixfbecker We have a lot to improve there, I still don't know about a specific thing with a significant performance impact.
Any help in measuring and solving this problem will be appreciated 🙏🏼

@rdsedmundo I'm pretty sure it isn't related, the extension is not involved in file saving. it's just adding new diagnostics when TypeScript creates his diagnostics.

**Comment by rdsedmundo** [comment]
It is, I disabled and the error is gone. I did a bisect as the author suggest, it's definitely this extension the culprit.

**Comment by felixfbecker** [comment]
@yoavbls  Given it blocks the UI, it leads me to believe that this must be happening in VS Code, since the extension runs in the extension host worker. So the only thing I can think of is that the amount (or frequency) of data the extension is giving VS Code overloads the UI process (or there is some inefficient code in VS Code).
I'd probably go at this by using the Devtools in VS Code to capture a perf profile while it is happening and see where the CPU is spending its time.

**Comment by aludvigsen** [comment]
Yes, the extension is nice, but it totally kills VS Code.

**Comment by yoavbls** [comment]
@rdsedmundo It's weird. It shouldn't affect the file saves. Do you see something that could cause it?
@felixfbecker that is a good idea. If someone wants to make some performance tests and spot the weak spots/functions that take the longest times to run it would be helpful.

I will investigate it deeper after the migration to a monorepo is completed

**Comment by RobertOstermann** [comment]
I haven't run into any performance issues yet, but haven't used the extension very much. Perhaps a short term solution for people running into this issue could be to have the extension run in a different process. Adding this to your settings.json should allow for the extension to use the second extension host process.

```json
"extensions.experimental.affinity": {
    "yoavbls.pretty-ts-errors": 1,
},
```

**Comment by kevinbailey25** [comment]
I will second this, vscode has been very sluggish lately with this extension. I've disabled it for now. This extension has been a MAJOR help with the ts errors for newer devs on my team, hope these issues can get resolved. Wish I had more free time to help.

**Comment by yoavbls** [comment]
v0.5 just published with a new caching mechanism 🕺🏼
Try it out, it should solve these performance issues
https://github.com/yoavbls/pretty-ts-errors/releases/tag/v0.5.0

**Comment by Pybast** [comment]
I'm facing similar performance problems today (never had them before), disabling / enabling the extension does fix / enable the issue.
I really like this extension so that's why I'm reporting it here

Extension version: 0.5.2
VS Code Version: 1.85.1 (Universal) Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2 Date: 2023-12-13T09:48:06.308Z (1 wk ago)
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 22.1.0

System infos: M1 MBP 32Go RAM

**Comment by Pybast** [comment]
After more research, it seems the performance issue is due to the `"typescript.tsserver.experimental.enableProjectDiagnostics": true` experimental feature. There is an ongoing bug where node_modules files get analysed by the typescript server and the found errors are reported in the `Problems` tab even when node_modules are excluded in the `tsconfig.json`.
I'm guessing that pretty-ts-errors is ran on all encountered problems which is a lot in this case.
