### ISSUE TITLE
Incorrect error formatting

### ISSUE THREAD

**Issue by Semigradsky** [yoavbls/pretty-ts-errors#50]
**Original error**
```
Argument of type '{ filters: Filters; } & T' is not assignable to parameter of type 'T & F'.
  Type '{ filters: Filters; } & T' is not assignable to type 'F'.
    '{ filters: Filters; } & T' is assignable to the constraint of type 'F', but 'F' could be instantiated with a different subtype of constraint '{ filters: Filters; }'.ts(2345)
```

**Screenshots**
![image](https://user-images.githubusercontent.com/1198848/234643532-660a90b1-7a6f-4058-98c1-f7f10b9f1d02.png)

**Describe the bug**
The problem in formatting `type 'F', but 'F' could` and `constraint '{ filters: Filters; }'.`

**Comment by yoavbls** [comment]
It was fixed in [v0.4.0](https://github.com/yoavbls/pretty-ts-errors/releases/tag/v0.4.0), take a look 🙂
