### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by mohammadgarmroodi** [yoavbls/pretty-ts-errors#58]
- Issue Type: `Performance`
- Extension Name: `pretty-ts-errors`
- Extension Version: `0.4.0`
- OS Version: `Windows_NT x64 10.0.19044`
- VS Code version: `1.78.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///c%3A/Users/LENOVO/AppData/Local/Temp/yoavbls.pretty-ts-errors-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by yoavbls** [comment]
I'm planning to address it soon by caching the formatted error messages,
I hope it'll also resolve this:
https://github.com/yoavbls/pretty-ts-errors/issues/36#issuecomment-1529845176

I'll update about it soon.

**Comment by tfrijsewijk** [comment]
I'm experiencing this as well on a moderately large codebase. My vscode is not showing any TypeScript hints for over a minute. Changes are hardly coming through.

Dou you have any idea what is causing the load? It should only format an error upon showing the dialog, why is it consuming so much during startup? On a small codebase there's no problem.

Thanks for your great work!

**Comment by yoavbls** [comment]
v0.5 just published with a new caching mechanism 🕺🏼
Try it out, it should solve these performance issues
https://github.com/yoavbls/pretty-ts-errors/releases/tag/v0.5.0
