### ISSUE TITLE
Formatting error with single quotes inside a string literal type

### ISSUE THREAD

**Issue by michaelstephendavies** [yoavbls/pretty-ts-errors#61]
**Describe the bug**
Hovering over the error in:

```typescript
const x: "' 'Oh no" = null;
```

The formatting is broken

> Type `null` is not assignable to type `"`'Oh no"'.

**Expected behavior**

> Type `null` is not assignable to type `"' 'Oh no"`.

**Original error**
<code>Type 'null' is not assignable to type '"' 'Oh no"'.ts(2322)</code>

**Screenshots**
<img width="454" alt="image" src="https://github.com/yoavbls/pretty-ts-errors/assets/1212291/4f3765d9-44cf-4181-b711-bca716c77e36">

**Comment by Aamir-Ansari-VESIT** [comment]
I would like to fix this bug

**Comment by yoavbls** [comment]
@BalthazarB you're welcome to do it 🙂

**Comment by MikeJakuszewski** [comment]
Is this still open?

**Comment by yoavbls** [comment]
@MikeJakuszewski yes

**Comment by MikeJakuszewski** [comment]
@yoavbls, what is the expected behavior we want? Do we want to remove the inner quotes? I think I found the error, it is under format/addMissingParentheses.ts

**Comment by yoavbls** [comment]
@MikeJakuszewski The expected behavior is without removing the inner quotes:
type `null` is not assignable to type `"' 'Oh no"`

You're welcome to try to fix it, and I can help in Discord if needed
Unfortunately, I don't think it's the `addMissingParentheses` function because it should called only when a type ends with ...

**Comment by yoavbls** [comment]
I'm pretty sure I fixed all the cases of string literal types that did not escape properly [here](https://github.com/yoavbls/pretty-ts-errors/commit/49449f3728b9bb05e02e1f74bdf6a28d50678b91#diff-4e3b338a97b4028106519668a3e2b95e77c345d6a742dee46d67f154b7a83997R15).

Give it a try with 0.5.2 and reopen this issue if you find new cases like this
