### ISSUE TITLE
Props in React Component

### ISSUE THREAD

**Issue by myagizmaktav** [yoavbls/pretty-ts-errors#65]
**Describe the bug**
When writing code in React, I often need to transfer props to the parent component. However, I sometimes forget which props need to be omitted when passing them to the parent component.

**Expected behavior**
I expect to have a clear and convenient way of determining which props should be omitted when passing them to the parent component.

```tsx
LanguagePicker.tsx

type languagePickerProps = {
  pickerProps?: DropDownPickerProps<Object>;

  // Omit<
  //   DropDownPickerProps<Object>,
  //   "multiple" | "setValue" | "value" | "items" | "open" | "setOpen"
  // >;
};

export const LanguagePicker = (props: languagePickerProps) => {
  // Component logic here
};


Footer.tsx

<LanguagePicker
  pickerProps={{
    style: {
      backgroundColor: "red",
    },
  }}
/>

```

**Screenshots**

<img width=300 src="https://github-production-user-asset-6210df.s3.amazonaws.com/115627863/242345108-c7597ca4-d494-4af1-9ff1-7bf0429fa739.png"/>

Props needs to be shown in code format I think.
<img width=300 src="https://github-production-user-asset-6210df.s3.amazonaws.com/115627863/242345186-7ae426b1-9337-4e56-9107-9e7d8f3fb5d5.png"/>

Please provide more context or additional information if necessary to help identify and resolve the issue.

**Comment by yoavbls** [comment]
Fixed in 0.5.2 🙂
