### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Angel-Dijoux** [yoavbls/pretty-ts-errors#74]
- Issue Type: `Performance`
- Extension Name: `pretty-ts-errors`
- Extension Version: `0.5.1`
- OS Version: `Linux x64 6.4.6-76060406-generic`
- VS Code version: `1.81.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///tmp/yoavbls.pretty-ts-errors-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by eplatek-safyr** [comment]
I just tried to re-enable the extension, it's working fine now.

I was testing with previous version of the extension to find which version caused the issue, but every version had the same issue, so I guess it was caused by another extension. Does it still happen to you @Angel-Dijoux  ?

**Comment by yoavbls** [comment]
@Angel-Dijoux Can you attach the profile file, please?
I thought we had already fixed it with the new caching mechanism here:
https://github.com/yoavbls/pretty-ts-errors/pull/62
I would like to dig into it when I have your profile file

**Comment by yoavbls** [comment]
I'm closing this since there is no response from the issue opener,
Feel free to reopen it if needed
