### ISSUE TITLE
Cannot install to a vscode remote server via ssh, press install and it always installing.

### ISSUE THREAD

**Issue by wszxdhr** [yoavbls/pretty-ts-errors#76]
**Describe the bug**
Cannot install to a vscode remote server via ssh, press install and it always installing.

**Expected behavior**
Extension can be installed to remote server.

**Original error**

**Screenshots**
![image](https://github.com/yoavbls/pretty-ts-errors/assets/11972255/804715ed-1b66-40df-9332-bdd0ab6d0a87)

**Comment by yoavbls** [comment]
Hi @wszxdhr,
Is it still happening? Can you provide any information for reproducing it?

**Comment by yoavbls** [comment]
I'm closing this since there is no response from the issue opener,
Feel free to reopen it if needed
