### ISSUE TITLE
The contributing guidelines on github are strange, why don't you change them?

### ISSUE THREAD

**Issue by orangeman7201** [yoavbls/pretty-ts-errors#78]
##  Now
[CONTRIBUTING.md](https://github.com/search?q=repo%3Ayoavbls%2Fpretty-ts-errors%20contributing&type=code) contains only the following one line, which has little content and does not function well as a guideline.
```
Contribute good stuff
```

Moreover, a link to this file is shown as a guideline on the following page.
* [Top of issues](https://github.com/yoavbls/pretty-ts-errors/issues)
* [Top of Pull Requests](https://github.com/yoavbls/pretty-ts-errors/pulls)
* [Screen for filling out an issue](https://github.com/yoavbls/pretty-ts-errors/issues/new?assignees=&labels=bug&projects=&template=bug_report.md&title=)

This is a capture of the current screen
Top of issues|Top of Pull Requests|Screen for filling out an issue
-|-|-
![Issues_·_yoavbls_pretty-ts-errors](https://github.com/oss-gate/workshop/assets/84920430/55f47b92-a531-4ad8-b955-1b78b59019ac)|![Pull_requests_·_yoavbls_pretty-ts-errors](https://github.com/yoavbls/pretty-ts-errors/assets/84920430/990b40f9-18cc-454c-b07e-ed81b77e2754)|![Cursor_と_New_Issue_·_yoavbls_pretty-ts-errors](https://github.com/oss-gate/workshop/assets/84920430/c8254eec-7378-4f09-b36c-1b8c9531a8e6)

## Expected

Would you change the content of CONTRIBUTING.md to the following?

```
* Any other contribution is welcome. Feel free to open any issue / PR you think.
* Bug reports should be filed in accordance with the bug report template.
```

**Comment by yoavbls** [comment]
Hi @orangeman7201, thank you for opening this issue,
Actually, I don't see any benefits from changing the contribution file to another one that doesn't help with opening PRs (and using templates for issues isn't important to me).

I will appropriate if someone changes the contribution file and adds things like debugging information like here:
https://github.com/yoavbls/pretty-ts-errors/blob/main/src/test/suite/errorMessageMocks.ts#L4

**Comment by yoavbls** [comment]
I added a link to the new tasks board to the CONTRIBUTING.md.
I'm closing this issue for now, but you're still welcome to open a PR with improvements to the contribution file or reopen the issue if needed 🙂
