### ISSUE TITLE
After vscode installs the Chinese language pack, the syntax highlighting is incorrect

### ISSUE THREAD

**Issue by weiShaoY** [yoavbls/pretty-ts-errors#83]
![686b66930dbf49d02c1db7a4acc4bec](https://github.com/yoavbls/pretty-ts-errors/assets/56295518/ebad0381-16eb-4292-8c3f-2166b1428da1)
![image](https://github.com/yoavbls/pretty-ts-errors/assets/56295518/c7dca808-644f-482c-a6f9-6e9b0fc3aa52)
![image](https://github.com/yoavbls/pretty-ts-errors/assets/56295518/67fa5b3c-d1de-44b6-8d82-4e90869ae08d)

As shown in the picture, after installation, the error highlighting is gone.

**Comment by yoavbls** [comment]
Unfortunately, it still doesn't support more locales and languages, and I'm looking for the best way to do so.
I'm closing it for now in favor of:
https://github.com/yoavbls/pretty-ts-errors/issues/27

**Comment by kevinramharak** [comment]
I have opened a discussion at #146, any input is welcome!
