### ISSUE TITLE
What is the minimum version it supports？

### ISSUE THREAD

**Issue by peterdaiweb** [yoavbls/pretty-ts-errors#87]
As the title, what is the minimum version it supports?
I can't install it in an old version of vscode 1.70.2

**Comment by yoavbls** [comment]
The minimum VSCode version required is v1.77
because we're using dynamic color variables that got in this version:
https://github.com/microsoft/vscode/pull/176312

Is it a real issue? If so I can write a fallback and use generic colors for versions lower than v1.77
