### ISSUE TITLE
solidarity

### ISSUE THREAD

**Issue by felixhaeberle** [yoavbls/pretty-ts-errors#89]
Hey @yoavbls,

I recognize you are from Israel and have been silent since the Hamas attack on the Israeli people.

I want to express my solidarity, and I hope you & your family are doing okay in those challenging times.
Your work is truly incredible, you have built a great piece of software that is making the lives of thousands of developers a lot easier.

I hope you will find peace in Israel & Palestina somehow in the future.

Best,
Felix

**Comment by yoavbls** [comment]
Thank you so much Felix! I am very excited to read that. ❤️
The Hamas attack on Israeli people was terrible, and we had a tough time here. 
I had to do my duty, so as you noticed, I wasn't available in recent months, but my family and I are okay, and I am gradually returning to my life and work.

I share your hope for peace.
Yoav
